### PR TITLE
Feature/fix http error reporting

### PR DESCRIPTION
**Pull request by marcinant**

### CODE REVIEW

**Comment by nlamirault** [comment]
Pull request closed ?

**Comment by marcinant** [comment]
Ehh I thought I can fix this PR easily. I'll reopen.
Keep in mind that as described above. This PR contains some unrelated code.

**Comment by marcinant** [comment]
Hmm cannot reopen. I'll try to make new PR.

**Comment by nlamirault** [comment]
OK

**Comment by marcinant** [comment]
Done and merged. Thank you.

**Pull request closed without merging**
